name: pt-env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.7.10
  - pytorch=1.11.0
  - pytorch-lightning=1.4.5
  - torchmetrics=0.5.1
  - torchvision=0.2.2
  - tqdm=4.62.2
  - scikit-learn=0.24.2
  - pillow=8.3.2
  - pandas=1.3.2